# Generated by Django 5.0.6 on 2024-06-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field", models.CharField(max_length=100, verbose_name="field")),
            ],
            options={
                "verbose_name": "тестовая модель",
                "verbose_name_plural": "тестовые модели",
            },
        ),
    ]
